kind: PersistentVolumeClaim                                                     
apiVersion: v1                                                                  
metadata:                                                                       
  name: pvc2                                                                  
spec:                                                                           
  storageClassName: nfs-client
  accessModes:                                                                  
    - ReadWriteMany                                                             
  resources:                                                                    
    requests:                                                                   
      storage: 50Mi 
