apiVersion: v1                                                                  
kind: Pod                                                                       
metadata:                                                                       
  name: cm-test-pod                                                           
spec:                                                                           
  containers:                                                                   
    - name: test-container                                                      
      image: k8s.gcr.io/busybox                                                 
      command: [ "/bin/sh", "-c", "sleep 600" ]                                       
      volumeMounts:                                                             
      - name: config-volume                                                     
        mountPath: /config                                                        
  volumes:                                                                      
    - name: config-volume                                                         
      configMap:                                                                    
        name: special-config                                                          
  restartPolicy: Never 
